name: two_d_project
description: "A new Flutter project."
publish_to: "none"

version: 2.0.0+5

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.7.2

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

  # Utilities
  intl: ^0.20.2
  http: ^1.3.0
  clipboard: ^0.1.3
  fluttertoast: ^8.2.12
  connectivity_plus: ^6.1.3
  audioplayers: ^6.4.0
  change_app_package_name: ^1.5.0
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  crypto: ^3.0.6
  carousel_slider: ^5.1.1
  marquee: ^2.3.0
  # google_sign_in: ^6.3.0
  # flutter_facebook_auth: ^7.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/2d.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/sinup/
    - assets/sounds/

  fonts:
    - family: Boldon
      fonts:
        - asset: fonts/boldon.ttf
    - family: Jasmine
      fonts:
        - asset: fonts/Roboto-SemiBold.ttf
